// ============================================================
//  SAFETY PATH – Firebase Configuration
//  Replace the firebaseConfig object below with your own
//  Firebase project credentials from:
//  https://console.firebase.google.com → Project Settings → Your Apps
// ============================================================

const firebaseConfig = {
  apiKey: "AIzaSyDmBHyZaTyE7jfGe_dymdZ7vef75RHabqU",
  authDomain: "safetypath-11cef.firebaseapp.com",
  projectId: "safetypath-11cef",
  storageBucket: "safetypath-11cef.firebasestorage.app",
  messagingSenderId: "377383297183",
  appId: "1:377383297183:web:aec2c418997d0d5c1682aa",
  measurementId: "G-R7L2Z0FV6X"
};

// Initialize Firebase
firebase.initializeApp(firebaseConfig);
const auth = firebase.auth();
const db = firebase.firestore();

// ============================================================
//  FIRESTORE DATABASE SCHEMA (for reference)
// ============================================================
//
//  COLLECTION: users
//  Document ID: uid (auto-generated by Firebase Auth)
//  Fields:
//    - uid: string
//    - name: string
//    - age: number
//    - gender: string         ("Female" | "Male" | "Non-binary" | "Prefer not to say")
//    - occupation: string
//    - phone: string          (E.164 format: +91XXXXXXXXXX)
//    - email: string
//    - emergencyContact: string
//    - emergencyPhone: string
//    - authMethod: string     ("phone" | "google")
//    - createdAt: timestamp
//    - lastLogin: timestamp
//    - privacyMode: boolean   (default: false)
//
// ============================================================
//  COLLECTION: crimeData  ← TO BE POPULATED LATER
//  Document ID: auto-id
//  Fields:
//    - area: string           (e.g., "Andheri West")
//    - lat: number
//    - lng: number
//    - crimeType: string      (e.g., "theft", "assault", "harassment")
//    - riskScore: number      (0–10 scale)
//    - timeSlot: string       ("morning" | "afternoon" | "evening" | "night")
//    - reportCount: number
//    - lastUpdated: timestamp
//    - source: string         (e.g., "Mumbai Police 2023")
//
// ============================================================
//  COLLECTION: routeRatings  ← TO BE POPULATED AFTER MAP PHASE
//  Document ID: auto-id
//  Fields:
//    - userId: string         (ref to users)
//    - fromLat: number
//    - fromLng: number
//    - toLat: number
//    - toLng: number
//    - routePolyline: string  (encoded polyline)
//    - safetyRating: number   (1–5)
//    - timeOfTravel: timestamp
//    - timeSlot: string       (derived from timeOfTravel)
//    - comment: string
//
// ============================================================
//  COLLECTION: emergencyAlerts  ← TO BE POPULATED IN PHASE 2
//  Document ID: auto-id
//  Fields:
//    - userId: string
//    - triggeredAt: timestamp
//    - location: GeoPoint
//    - resolvedAt: timestamp | null
//    - resolved: boolean
//    - voiceVerified: boolean
// ============================================================
